import { Globe, Code2, BrainCircuit, Database, Wrench, Sparkles } from 'lucide-react';
import { useInView } from '../hooks/useInView';
const SOFT_SKILLS = ['Communication', 'Problem Solving', 'Teamwork', 'Adaptability', 'Continuous Learning'];
const TECH_STACK = [
  { title: 'ML & DATA', icon: <BrainCircuit size={16} />, skills: ['Pandas', 'NumPy', 'Scikit-learn', 'OpenCV', 'MediaPipe', 'NLP'] },
  { title: 'DEVELOPMENT', icon: <Code2 size={16} />, skills: ['Java', 'JavaScript', 'Python', 'React', 'HTML5', 'CSS3'] },
  { title: 'DATABASES', icon: <Database size={16} />, skills: ['MySQL', 'MongoDB', 'SQL', 'Database Management'] },
  { title: 'TOOLS', icon: <Wrench size={16} />, skills: ['Git', 'GitHub', 'Bootstrap', 'Data Structures'] },
];
function SkillCategory({ title, icon, skills, index }: { title: string; icon: React.ReactNode; skills: string[]; index: number }) { const { ref, inView } = useInView(); return <div ref={ref} className="card-3d-depth gradient-border-card p-6" style={{ opacity: inView ? 1 : 0, transform: inView ? 'translateY(0)' : 'translateY(30px)', transition: `opacity .6s ease, transform .6s ease ${index * 100}ms` }}><div className="flex items-center gap-2.5 mb-5"><div className="p-2 bg-primary/10 rounded-lg text-primary">{icon}</div><h3 className="font-bold text-foreground uppercase tracking-wider text-sm">{title}</h3></div><div className="flex flex-wrap gap-2">{skills.map(skill => <span key={skill} className="px-3 py-1.5 bg-muted/40 border border-border/50 rounded-full text-[13px] font-medium">{skill}</span>)}</div></div>; }
export function Skills() { const { ref, inView } = useInView(); return <section id="stack" className="pt-12"><div ref={ref} className={`reveal ${inView ? 'in-view' : ''}`}><h2 className="section-heading">Skills</h2><div className="flex flex-col md:flex-row gap-12 lg:gap-20"><div className="w-full md:w-56 shrink-0"><div className="flex items-center gap-3 text-xl font-bold text-foreground mb-10"><div className="p-2 bg-primary/10 rounded-lg"><Sparkles className="text-primary" size={20} /></div>Profile</div><div className="mb-12"><div className="flex items-center gap-2 font-bold text-foreground mb-6"><Globe size={16} className="text-primary" />Languages</div><div className="space-y-4 text-sm"><div className="flex justify-between items-center py-2 px-3 bg-muted/30 rounded-lg border border-border/30"><span className="text-foreground font-medium">Hindi</span><span className="text-primary font-medium text-xs uppercase tracking-wide">Native</span></div><div className="flex justify-between items-center py-2 px-3 bg-muted/30 rounded-lg border border-border/30"><span className="text-foreground font-medium">English</span><span className="text-muted-foreground text-xs">Professional</span></div></div></div><div><div className="font-bold text-foreground mb-6">Soft Skills</div><div className="flex flex-col gap-2.5 items-start">{SOFT_SKILLS.map(skill => <span key={skill} className="px-4 py-1.5 bg-primary/10 text-primary border border-primary/20 rounded-full text-[13px] font-medium">{skill}</span>)}</div></div></div><div className="flex-1"><div className="font-bold text-foreground mb-8 text-lg">Tech Stack</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{TECH_STACK.map((col, i) => <SkillCategory key={col.title} {...col} index={i} />)}</div></div></div></div></section>; }
